set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES STM32_CLT_ROOT)
if(NOT DEFINED STM32_CLT_ROOT)
    message(FATAL_ERROR "Pass -DSTM32_CLT_ROOT=<installed CubeCLT directory>")
endif()
file(TO_CMAKE_PATH "${STM32_CLT_ROOT}" STM32_CLT_ROOT)
set(ARM_BIN "${STM32_CLT_ROOT}/GNU-tools-for-STM32/bin")
set(CMAKE_C_COMPILER "${ARM_BIN}/arm-none-eabi-gcc.exe")
set(CMAKE_ASM_COMPILER "${ARM_BIN}/arm-none-eabi-gcc.exe")
set(CMAKE_OBJCOPY "${ARM_BIN}/arm-none-eabi-objcopy.exe")
set(CMAKE_SIZE "${ARM_BIN}/arm-none-eabi-size.exe")
